Coins working
BrendenDomingo/Coop-de-Gras pull request #33
Opened 2023-04-27 01:19 UTC by BrendenDomingo

2023-04-28 05:39 UTC, Kharjai requested changes

2023-04-28 05:39 UTC, Kharjai commented on Assets/Sprites/New Material.mat
Can we give this a more descriptive name? I'm guessing this was just auto generated with the prefab or something.

2023-05-01 22:47 UTC, BrendenDomingo commented on Assets/Sprites/New Material.mat
That's not supposed to be there lol, ill remove it.

2023-05-03 01:07 UTC, Kharjai approved these changes

2023-05-03 01:10 UTC, merged